### ISSUE TITLE
Missing values display when verbose activated

### ISSUE THREAD

**Issue by eragot** [ThalesGroup/helm-spray#43]
Hi,

Should be good to display the umbrella chart when a parsing error occur in order to see which line in the chart causing problem.
Currently only the line number is display with a message but impossible to know which directive in the chart is wrong.

Thanks a lot
BR

**Comment by pamiel** [comment]
While this feature is now available for Spray v3.x since https://github.com/ThalesGroup/helm-spray/pull/45, it has been "lost" when moving to Spray v4 => keeping the issue open.

**Comment by cvila84** [comment]
Also fixed in v4
