### ISSUE TITLE
Table listing dependencies in verbose mode not correctly filled in debug mode

### ISSUE THREAD

**Issue by pamiel** [ThalesGroup/helm-spray#44]
The table shown when using the `--verbose` option is not correctly filled when the `--debug` option is used in complement or instead of `--verbose`: all revisions are set to "None" and all statuses are set to "Not deployed".

**Comment by pamiel** [comment]
Solved by https://github.com/ThalesGroup/helm-spray/pull/59 on Spray v3.x.

Keeping it open for checking whether it is also to be fixed on Spray v4.x or not (code base has changed a lot for Spray v4)

**Comment by cvila84** [comment]
Also fixed in v4
