### ISSUE TITLE
Install fails with plugin metadata (plugin.yaml) missing

### ISSUE THREAD

**Issue by domahoneyii** [ThalesGroup/helm-spray#47]
Run `helm plugin install https://github.com/gemalto/helm-spray`
Get `Error: plugin metadata (plugin.yaml) missing`

Results of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

**Comment by cvila84** [comment]
Indeed, the remote installation via https in not yet supported. We would need to create a hook in plugin.yaml calling a script that will build the plugin according to the OS where the installation is requested.

I removed the incorrect part of README.md that was mentionning remote installation is supported.

However, developer install is feasible (in using the Makefile) as described in the documentation

**Comment by cvila84** [comment]
v4 is out today and can be installed normally with helm plugin install command !
