### ISSUE TITLE
Helm Spray does not support helmV3

### ISSUE THREAD

**Issue by umardev0** [ThalesGroup/helm-spray#48]
Is this compatible with helm 3?
I have helm 3 and cannot use spray.

when I run `helm spray` I get this error:

`Error: fork/exec /home/USER/.local/share/helm/plugins/helm-spray/helm-spray: no such file or directory`

**Comment by jroucheton** [comment]
Hey @umardev0,

For now, helm spray has not been tested with Helm v3.

**Comment by umardev0** [comment]
I don't know if this is relevant here or not as its not helmV3 issue but I fixed the above error by putting helm-spray binary from the downloaded tar file into `/home/USER/.local/share/helm/plugins/helm-spray/`.

I installed the plugin by `helm plugin install https://github.com/gemalto/helm-spray` but for some reason there was no helm-spray binary in `..plugins/helm-spray/` directory.

**Comment by umardev0** [comment]
As for helmV3, when I try to use `helm spray [chartname]` it gives this error:

`Error loading chart "[chartname]": apiVersion 'v2' is not valid. The value must be "v1"
Error: plugin "spray" exited with error`

**Comment by atotala** [comment]
I am also facing the same issue, would be great if this issue can be fixed.

**Comment by cvila84** [comment]
hello, next major helm-spray release will support helm3. we should be able to deliver it in the upcoming days !

**Comment by cvila84** [comment]
hello, v4 is out today with support for helm 3 !
