### ISSUE TITLE
Spray the deployment across multiple namespaces

### ISSUE THREAD

**Issue by satyarths** [ThalesGroup/helm-spray#50]
Can I specify the namespace to deploy the subchart in to in `dependencies.yaml` . My usecase is to be able to separate the application releases from the monitoring releases.

**Comment by pamiel** [comment]
No, you cannot: the `dependencies.yaml` file format is specified by Helm, and there is no room to provide a namespace information there.

However, you can set the namespace directly in your resource's yaml file, when you want to target a specific namespace:
- For the resources to deploy in the namespace specified through the Spray's `--namespace` option: regular `metadata`
```
apiVersion: v1
kind: Service
metadata:
  name: abc
```
- For the resources to deploy in another specific namespace (different from the one specified through the Spray's `--namespace` option): add the `metadata.namespace`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xyz
  namespace: monitoring
[...]
```
You can even play with the values to have a dynamic namespace name, or even use "{{ .Release.Name }}-monitoring" to get a name inheriting from the namespace provided through the Spray's `--namespace` option

**Comment by cvila84** [comment]
Closing as it is not something which can be handled by helm-spray
