### ISSUE TITLE
exec error

### ISSUE THREAD

**Issue by phamngocthanhtrung** [ThalesGroup/helm-spray#61]
hi, 
I am a rookie in deployments with HelmCharts. Currently I'm trying to determine the order of the Umbrella Charts/Subcharts with helspray. I was able to install the plugin successfully 

user@MacBook-Pro helm-dir % helm plugin list
NAME 	VERSION	DESCRIPTION                                                                    
spray	4.0.1  	Helm plugin for upgrading sub-charts from umbrella chart with dependency orders

but until using it with $ helm spray [flags] CHART I get an exec error. 

Error: fork/exec /Users/ngocthanhtrungpham/Library/helm/plugins/helm-spray/bin/helm-spray: no such file or directory

i'm not familiar with helm plugins and don't know if i have to set something in the environment variable. It seems that it does not find helmet spray in the bin folder. 
I use osx operating system and deploy it as test with minikube
best regards

**Comment by cvila84** [comment]
hello,

First, thank you for using helm-spray !

Unfortunately, we are for now only building helm-spray for windows and linux (as you can see [here](https://github.com/ThalesGroup/helm-spray/releases/latest)).

That said, the plugin installation should return an error saying no executable could be installed in this case, to avoid this misunderstanding, so we will work on this improvement.

For the support on mac, I need to find such a machine and make some tests. I will update this ticket whenever I can do something about it.

**Comment by cvila84** [comment]
Closed as #65 was merged
