### ISSUE TITLE
Install script fails with '[: unexpected operator' errors

### ISSUE THREAD

**Issue by Elassyo** [ThalesGroup/helm-spray#71]
When attempting to install helm-spray with  `helm plugin install https://github.com/ThalesGroup/helm-spray` , the install may fail on certain platform, with the following errors:
```
scripts/install_plugin.sh: 9: [: Linux: unexpected operator
scripts/install_plugin.sh: 11: [: Linux: unexpected operator
scripts/install_plugin.sh: 28: [: Linux: unexpected operator
scripts/install_plugin.sh: 28: [: Linux: unexpected operator
```

I believe this is caused by using Bash specific syntax while using `/bin/sh` in the script shebang.
The reason the script works on some platform and not others might be that some platform symlink `/usr/bin/sh` to `/usr/bin/bash` whereas others might have the classic sh installed instead.

**Comment by cvila84** [comment]
Thanks for the PR !
