### ISSUE TITLE
Error: fork/exec /root/.local/share/helm/plugins/helm-spray/bin/helm-spray: no such file or directory

### ISSUE THREAD

**Issue by alokrbl** [ThalesGroup/helm-spray#82]
I have installed spray plugin in container with image image dtzar/helm-kubectl:latest
 
helm plugin install https://github.com/ThalesGroup/helm-spray --version 4.0.10
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /builds/MyContainerImages/tests/cd-tests.tmp/SRV_KUBECONFIG
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /builds/MyContainerImages/tests/cd-tests.tmp/SRV_KUBECONFIG
Downloading and installing spray v4.0.10 for Linux...
Installed plugin: spray

But my helm spray command fails

helm spray --help
Error: fork/exec /root/.local/share/helm/plugins/helm-spray/bin/helm-spray: no such file or directory

Any help is appreciated.

**Comment by cvila84** [comment]
Hello,

This is because the docker image you are using to launch the command is based on alpine which does not have required libc libs.

Either change your image for a libc based one or install libc6-compat alpine package (but I don't know the actual level of compatibility with libc for this package)

```
$ docker run -it dtzar/helm-kubectl
589ec9559b15:/config# helm plugin install https://github.com/ThalesGroup/helm-spray --version 4.0.10
Downloading and installing spray v4.0.10 for Linux...
Installed plugin: spray
589ec9559b15:/config# helm spray --help
Error: fork/exec /root/.local/share/helm/plugins/helm-spray/bin/helm-spray: no such file or directory
589ec9559b15:/config# apk add libc6-compat
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/1) Installing libc6-compat (1.2.3-r4)
OK: 31 MiB in 45 packages
589ec9559b15:/config# helm spray --help

This command upgrades sub charts from an umbrella chart supporting deployment orders.
A release is created for each subchart
[...]
```

**Comment by alokrbl** [comment]
Thanks Christophe. it works now
